# Generated by Django 4.1.4 on 2022-12-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.BooleanField(verbose_name='Value'),
        ),
    ]
