# Generated by Django 4.1.4 on 2022-12-16 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('poll', '0003_alter_category_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='account.account'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='poll.category'),
        ),
    ]
