# Generated by Django 4.1.4 on 2022-12-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_poll_account_alter_poll_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
