# Generated by Django 4.1.4 on 2022-12-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_remove_vote_poll_vote_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
    ]
