# Generated by Django 4.1.4 on 2022-12-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_vote_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
    ]
