# Generated by Django 4.1.4 on 2022-12-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_alter_vote_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='value',
        ),
    ]
