# Generated by Django 3.2.16 on 2023-01-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_choice_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
