# Generated by Django 4.1.4 on 2023-01-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_remove_vote_dislikes_remove_vote_likes_like_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='like',
            name='vote',
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
